mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import url
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    path('treatment/', include('treatment.urls')),
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

treatment/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'treatment'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pacient_id>/', views.pacient, name='pacient'),
    path('calendar/', views.calendar, name='calendar'),
    path('pacienti/', views.pacienti, name='pacienti'),
    path('deleted/<int:pacient>', views.deleted, name='deleted'),
]

treatment/models.py
from django.utils.translation import gettext as _
from django.db import models
from django.utils import timezone
import datetime

class Personal(models.Model):
    tip = models.CharField(max_length=50)
    nr = models.IntegerField(default=1)
    def __str__(self):
        return self.tip

class Cabinet(models.Model):
    personal = models.ForeignKey(Personal, on_delete=models.CASCADE)
    nume = models.CharField(max_length=50)
    paturi = models.IntegerField(default=1)
    def __str__(self):
        return self.nume

class Aparat(models.Model):
    cabinet = models.ForeignKey(Cabinet, on_delete=models.CASCADE)
    nume = models.CharField(max_length=50)
    nr = models.IntegerField(default=1)
    max_paturi = models.IntegerField(default=1)
    max_regiuni = models.IntegerField(default=1)
    pregatire_pacient = models.IntegerField(default=5)
    def __str__(self):
        return self.nume

class Procedura(models.Model):
    aparat = models.ForeignKey(Aparat, on_delete=models.CASCADE)
    nume = models.CharField(max_length=50)
    asistent_prezent = models.BooleanField(default=False)
    timpi = models.TextField(default='5')
    regiuni = models.TextField(default='tot')
    prioritate = models.IntegerField(default=0)
    def __str__(self):
        return self.nume
    def lista_regiuni(self):
        if self.regiuni != "tot":
            return sorted(self.regiuni.split(','))
    def lista_timpi(self):
        listaT = self.timpi.split(',')
        if len(listaT) > 1:
            listaInt = []
            for timp in listaT:
                listaInt.append(int(timp))
            return sorted(listaInt, reverse=True)

class Pacient(models.Model):
    pacient_id = models.IntegerField()
    pac_id = models.IntegerField(default=0)
    nume = models.CharField(max_length=50, default="")
    activ = models.BooleanField(default=True)
    aparate = models.TextField(default='-')
    intervale_ocupate = models.TextField(default='-')
    ambulator = models.BooleanField(default=False)
    selectii = models.TextField(default='-')
    good = models.TextField(default='-')
    bad = models.TextField(default='-')
    date_added = models.DateField(_("Date"), default=datetime.date.today)
    def __str__(self):
        return self.nume
    def fisa_electronica(self):
        proceduri = Procedura.objects.all()
        #remove unselected procedures from selections
        details = []
        selections = self.selectii
        for procedura in proceduri:
            firstIndex = selections.find(procedura.nume)
            lastIndex = selections.rfind(procedura.nume)
            if firstIndex != -1 and firstIndex == lastIndex:
                timeString = procedura.nume + ":ztimp"
                restOfString = selections[firstIndex:].find("||")
                if selections.startswith(timeString,firstIndex):
                    if restOfString == -1:
                        selections = selections[:firstIndex]
                    else:
                        actualIndex = firstIndex + restOfString + 2
                        selections = selections[:firstIndex]+selections[actualIndex:]
        lista_selectii = selections.split('||')
        selectii_filtrate = []
        for selectie in lista_selectii:
            if "ztimp" in selectie:
                selectie = selectie.replace("ztimp:","") + "\'"
            selectie = selectie.replace(":"," ")
            selectii_filtrate.append(selectie)
        return selectii_filtrate[2:-1]

class Program(models.Model):
    cabinet = models.ForeignKey(Cabinet, on_delete=models.CASCADE)
    ora = models.CharField(max_length=5)
    locuri = models.IntegerField()
    pacienti = models.TextField(default='')
    def __str__(self):
        return self.cabinet.nume + ":ora " + str(self.ora) + ":liber "+str(self.locuri)

treatment/views.py
from django.shortcuts import render
from django.urls import reverse
import time
import random

from .models import Personal, Cabinet, Aparat, Procedura, Pacient, Program

from .create_fisa import programPacient, remove, getTotal4SelectedProc, checkForAvailableSpot, getFinishTime

def index(request):
    proceduri = Procedura.objects.order_by('nume')
    return render(request, 'treatment/index.html', {'proceduri': proceduri})

def pacient(request, pacient_id):
    selectii = request.POST.get('mytext', False)
    if selectii:
        pac_id = int(str(random.randint(10000,99999))+str(int(time.time())))
        existaPacient = Pacient.objects.filter(selectii=selectii).filter(activ=True)
    else:
        existaPacient = []
        existaPacient.append(Pacient.objects.get(pacient_id=pacient_id))
    if len(existaPacient) > 0 :
        text = []
        good = []
        pacient = existaPacient[0]
        tempgood = pacient.good.split('||')
        for tmp in tempgood:
            if len(tmp) == 0:
                continue
            good.append(list(filter(None, tmp.split('[['))))
        bad = list(filter(None, pacient.bad.split('||')))
    else:
        text = programPacient(selectii, pacient_id, pac_id)
        pacient = Pacient.objects.get(pacient_id=pacient_id)
        goodtext = ""
        badtext = ""
        good = []
        bad = []
        for txt in text:
            if "could not save" in txt:
                txtparts = txt[15:].replace(":"," - ")
                txtparts = txtparts + " minute"
                bad.append(txtparts)
                badtext = badtext + "||" + txtparts
            else:
                txtparts = txt.split(':')
                newtxt = []
                if len(txtparts[1]) == 3:
                    newtxt.append(txtparts[0][:2] + ":" + txtparts[0][2:] + "-" + "0" + txtparts[1][:1] + ":" + txtparts[1][1:])
                    goodpart = "[["+txtparts[0][:2] + ":" + txtparts[0][2:] + "-" + "0" + txtparts[1][:1] + ":" + txtparts[1][1:]+"[["
                else:
                    newtxt.append(txtparts[0][:2] + ":" + txtparts[0][2:] + "-" + txtparts[1][:2] + ":" + txtparts[1][2:])
                    goodpart = "[["+txtparts[0][:2] + ":" + txtparts[0][2:] + "-" + txtparts[1][:2] + ":" + txtparts[1][2:]+"[["
                goodpart = goodpart + txtparts[2]+"[[" + txtparts[3]+"[[" + txtparts[4]+"[["
                newtxt.append(txtparts[2])
                newtxt.append(txtparts[3])
                newtxt.append(txtparts[4])
                goodtext = goodtext + "||" + goodpart
                good.append(newtxt)
                print(newtxt)
        pacient.good = goodtext + "||"
        pacient.bad = badtext + "||"
        pacient.save()
    return render(request, 'treatment/pacient.html', {'good': good, 'bad': bad, 'pacient': pacient})

def calendar(request):
    cabinete = Cabinet.objects.order_by('nume')
    programari = []
    for cabinet in cabinete:
        programari_cabinet = Program.objects.filter(cabinet=cabinet).order_by('ora')
        rows = []
        for programare in programari_cabinet:
            row = []
            row.append(cabinet.nume)
            if len(programare.ora) == 3:
                row.append("0"+programare.ora[:1]+":"+programare.ora[1:])
            else:
                row.append(programare.ora[:2]+":"+programare.ora[2:])
            id_programati = programare.pacienti.split('-')
            nume_pacienti = []
            for id in id_programati:
                if len(id) == 0 :
                    continue
                nume = Pacient.objects.get(pacient_id=str(id))
                nume_pacienti.append(nume.nume)
            row.append(nume_pacienti)
            rows.append(row)
        programari.append(rows)
    context = {'cabinete': cabinete, 'programari': programari}
    return render(request, 'treatment/calendar.html', context)

def pacienti(request):
    pacienti = Pacient.objects.filter(activ=True).order_by('nume')
    context = {'pacienti': pacienti}
    return render(request, 'treatment/lista_pacienti.html', context)

def deleted(request,pacient):
    #sterge pacient
    om = remove(pacient)
    context = {'pacient': om.nume}
    return render(request, 'treatment/pacient_sters.html', context)

treatment/templates/home.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url={% url 'treatment:calendar' %}" /> 
</head>
<body>
</body>
</html>

treatment/templates/treatment/calendar.html
{% load static %}
<head>
    <title>Listă cabinete</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'treatment/app.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'treatment/style.css' %}">
</head>

<body>
	<div id="mySidenav" class="sidenav">
		<img src="https://lh3.googleusercontent.com/bgvEYPZYwrgw9lg3BeD4m5MG61fE52sTDJi9dvZVbUHmiKC-dJJYMzt6k_Xsirw5tnWwfby1hbgY_pfkdPO1uwvsc4gHuD0QPVymlfh8MAQ_esEXnRcKdrgGgezKHQyXQah4YJEt-w=w2400" alt="Patient Base" style="width:250px;height:200px;"/>
		<a href="{% url 'treatment:index' %}">Adăugare fișă</a>
		<a href="{% url 'treatment:pacienti' %}">Vizualizare pacienți</a>
		<a onclick="toggleNav()">&larr; <i>ascunde meniu</i></a>
	</div>
	<div id="main">
		<div class="white-block">
			<span class="menu-button" onclick="toggleNav()">&larr;Meniu</span>
			<br><br>
			<div class="dropdown">
				<button onclick="dropDown()" class="dropbtn">Click pentru selecție cabinet</button>
				<div id="myDropdown" class="dropdown-content">
					{% for cabinet in cabinete %}
						<a onclick="toggleCabinet({{ cabinet.pk }})">{{ cabinet }}</a>
					{% endfor %}
				</div>
			</div>
			{% for cabinet in cabinete %}
				<div class="cabinet-content" id="{{ cabinet.pk }}">
					<h2>{{ cabinet }}</h2>
					<table>
						<tr>
							<th>Ora</th>
							<th>Pacienți</th>
						</tr>
						{% for rows in programari %}
							{% for row in rows %}
								{% ifequal row.0 cabinet.nume %}
									<tr>
										<td>{{ row.1 }}</td>
										<td>
												{% for pacient in row.2 %}
													<p>{{ pacient }}</p>
												{% endfor %}
										</td>
									</tr>
								{% endifequal %}
							{% endfor %}
						{% endfor %}
					</table>
				</div>
			{% endfor %}
		</div>
	</div>
</body>

treatment/templates/treatment/index.html
{% load static %}
<head>
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<title>Pacient nou</title>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    	<script src="http://code.jquery.com/ui/1.9.1/jquery-ui.min.js" type="text/javascript"></script>
    	<script src="{% static 'treatment/app.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'treatment/style.css' %}">
</head>
<body>
	<div id="mySidenav" class="sidenav">
		<img src="https://lh3.googleusercontent.com/bgvEYPZYwrgw9lg3BeD4m5MG61fE52sTDJi9dvZVbUHmiKC-dJJYMzt6k_Xsirw5tnWwfby1hbgY_pfkdPO1uwvsc4gHuD0QPVymlfh8MAQ_esEXnRcKdrgGgezKHQyXQah4YJEt-w=w2400" alt="Patient Base" style="width:250px;height:200px;"/>
		<a href="{% url 'treatment:pacienti' %}">Vizualizare pacienți</a>
		<a href="{% url 'treatment:calendar' %}">Vizualizare cabinete</a>
		<a onclick="toggleNav()">&larr; <i>ascunde meniu</i></a>
		<a id="save" onclick="submitSelections()">Programează</a>
	</div>
	<div id="main">
		<div class="white-block">
			<span class="menu-button" onclick="toggleNav()">&larr;Meniu</span>
			<br>
			<div class="checkboxlist">
				<br>
				<form>
					<input type="text" name="field1" placeholder="Prenume și nume" id="inputname" value="">
				</form>
				<label class="radio-label">ambulatoriu
					<input type="radio" name="ambulator" value="ambulator:true" checked>
					<span class="radiomark"></span>
				</label>
				<label class="radio-label">internat
					<input type="radio" name="ambulator" value="ambulator:false" class="internat" checked>
					<span class="radiomark"></span>
				</label>
				<br><br>
				{% for procedura in proceduri %}
					<button class="accordion">
						{{ procedura.nume }}
					</button>
					<div class="panel">
						{% if procedura.lista_timpi %}
							<p>
								Minute/procedura:
								{% for timp in procedura.lista_timpi %}
									<label class="radio-label">{{ timp }}
										<input type="radio" name="timp:{{ procedura }}" value="{{ procedura }}:ztimp:{{ timp }}" checked>
										<span class="radiomark"></span>
									</label>
								{% endfor %}
							</p>
						{% endif %}
						{% if procedura.lista_regiuni %}
							<form class="regions">
								{% for regiune in procedura.lista_regiuni %}
									<br>
									<label class="checkbox-label">{{ regiune }}
										<input type="checkbox" value="{{ procedura }}:{{ regiune }}">
										<span class="boxmark"></span>
									</label>
								{% endfor %}
							</form>
						{% else %}
							<label class="checkbox-label">
								<input type="checkbox" value="{{ procedura }}">
								<span class="boxmark"></span>
							</label>
							<br>
						{% endif %}
					</div>
				{% endfor %}
			</div>
			<form action="#" method="post" id="form_id" style="display: none">
				{% csrf_token %}
				<input type="text" name="mytext" id="mytext" value="5" /><br />
				<input type="submit" value="Vote" />
			</form>
		</div>
	</div>
	<script>
		function getValueUsingParentTag(){
			var chkArray = [];
			$(".checkboxlist input:checked").each(function() {
				chkArray.push($(this).val());
			});
			var numePacient = document.getElementById('inputname').value;
			if(numePacient.length>0){
				var selected;
				selected = chkArray.join('||') ;
				var finalArray = [];
				if(selected.length > 0){
					selected = "Nume:"+numePacient+"||"+selected;
					var ts = Math.round((new Date()).getTime() / 1000);
					var url = "{% url 'treatment:pacient' 123 %}".replace('123', ts);
					document.getElementById('form_id').action = url;
					document.getElementById("mytext").value = selected;
					document.getElementById("form_id").submit();
					$('#inputname').val('ATENȚIE! AU RĂMAS SELECȚIILE DE LA PACIENTUL ANTERIOR.');
				}else{
					alert( "Nu poți adăuga pacient fără proceduri." );
				}
			}else{
				alert( "Numele pacientului lipsește!" );
			}
		}

		function submitSelections(){
			if (confirm("Sigur vrei să salvezi?")) {
				getValueUsingParentTag();
			}
		}
	</script>
</body>

treatment/templates/treatment/lista_pacienti.html
{% load static %}
<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Listă pacienți</title>
		<script src="{% static 'treatment/app.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'treatment/style.css' %}">
</head>
<body>
	<div id="mySidenav" class="sidenav">
		<img src="https://lh3.googleusercontent.com/bgvEYPZYwrgw9lg3BeD4m5MG61fE52sTDJi9dvZVbUHmiKC-dJJYMzt6k_Xsirw5tnWwfby1hbgY_pfkdPO1uwvsc4gHuD0QPVymlfh8MAQ_esEXnRcKdrgGgezKHQyXQah4YJEt-w=w2400" alt="Patient Base" style="width:250px;height:200px;"/>
		<a href="{% url 'treatment:index' %}">Adăugare fișă</a>
		<a href="{% url 'treatment:pacienti' %}">Vizualizare pacienți</a>
		<a href="{% url 'treatment:calendar' %}">Vizualizare cabinete</a>
		<a onclick="toggleNav()">&larr; <i>ascunde meniu</i></a>
	</div>
	<div id="main">
		<div class="white-block">
			<span class="menu-button" onclick="toggleNav()">&larr;Meniu</span>
			{% if pacienti %}
				<h2>Pacienți programați: {{ pacienti|length }}</h2>
			{% else %}
				<h2>Nu există pacienți programați.</h2>
			{% endif %}
			{% for p in pacienti %}
				<br>
				<i>{{ p.date_added|date:'d-m-Y' }}</i><br>
				<form action="{% url 'treatment:pacient' p.pacient_id %}" method="post" class="patient-form">
					{% csrf_token %}
					<input type="submit" value="{{ p }}" style="background-color:#F2FF49; width:60vw; overflow-x: auto;"/>
				</form>
				<form action="{% url 'treatment:deleted' p.pacient_id %}" method="post" class="patient-form">
					{% csrf_token %}
					<input type="submit" value="Șterge pacient" onclick="return confirm('Sigur vrei să ștergi acest pacient?');" style="background-color:#CCFF66; width:60vw;"/>
				</form>
				<br>
			{% endfor %}
		</div>
	</div>
</body>

treatment/templates/treatment/pacient.html
{% load static %}
<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Pacient</title>
		<script src="{% static 'treatment/app.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'treatment/style.css' %}">
</head>
<body>
	<div id="mySidenav" class="sidenav">
		<img src="https://lh3.googleusercontent.com/bgvEYPZYwrgw9lg3BeD4m5MG61fE52sTDJi9dvZVbUHmiKC-dJJYMzt6k_Xsirw5tnWwfby1hbgY_pfkdPO1uwvsc4gHuD0QPVymlfh8MAQ_esEXnRcKdrgGgezKHQyXQah4YJEt-w=w2400" alt="Patient Base" style="width:250px;height:200px;"/>
		<a href="{% url 'treatment:index' %}">Adăugare fișă</a>
		<a href="{% url 'treatment:pacienti' %}">Vizualizare pacienți</a>
		<a href="{% url 'treatment:calendar' %}">Vizualizare cabinete</a>
		<a onclick="toggleNav()">&larr; <i>ascunde meniu</i></a>
	</div>
	<div id="main">
		<div class="white-block">
			<span class="menu-button" onclick="toggleNav()">&larr;Meniu</span>
			<h1>{{ pacient.nume }}</h1>
			<p> {{ pacient.date_added }}</p>
			<p><i>*Timpii includ pregătire aparat și îmbrăcare/dezbrăcare.</i></p>
			<p>Programări salvate:</p>
			<div style="overflow-x:auto;display:block;" class="cabinet-content">
				<table>
					<tr>
						<th>Programare</th>
						<th>Cabinet</th>
						<th>Aparat</th>
						<th>Minute</th>
					</tr>
					{% for txt in good %}
						<tr>
							{% for txtpart in txt %}
								<td>{{ txtpart }}</td>
							{% endfor %}
						</tr>
					{% endfor %}
				</table>
			</div>
			<br>
			{% if bad %}
				<p>Procedurile care nu au putut fi salvate:</p>
				<ul>
				{% for txt in bad %}
					<li>{{ txt }}</li>
				{% endfor %}
				</ul>
			{% endif %}
			<form id="deletebutton" action="{% url 'treatment:deleted' pacient.pacient_id %}" method="post">
				{% csrf_token %}
				<input type="submit" value="Șterge din program" onclick="return confirm('Sigur vrei să ștergi acest pacient?');"/>
			</form>
			<div class="fisa">
				<h3><u>Fișă electronică</u></h3>
				{% for selectie in pacient.fisa_electronica %}
					<p>
						{{ selectie }}
					</p>
				{% endfor %}
			</div>
		</div>
	</div>
</body>

treatment/templates/treatment/pacient_sters.html
{% load static %}
<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Pacient șters</title>
		<script src="{% static 'treatment/app.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'treatment/style.css' %}">
</head>
<body>
	<div id="mySidenav" class="sidenav">
		<img src="https://lh3.googleusercontent.com/bgvEYPZYwrgw9lg3BeD4m5MG61fE52sTDJi9dvZVbUHmiKC-dJJYMzt6k_Xsirw5tnWwfby1hbgY_pfkdPO1uwvsc4gHuD0QPVymlfh8MAQ_esEXnRcKdrgGgezKHQyXQah4YJEt-w=w2400" alt="Patient Base" style="width:250px;height:200px;"/>
		<a href="{% url 'treatment:index' %}">Adăugare fișă</a>
		<a href="{% url 'treatment:pacienti' %}">Vizualizare pacienți</a>
		<a href="{% url 'treatment:calendar' %}">Vizualizare cabinete</a>
		<a onclick="toggleNav()">&larr; <i>ascunde meniu</i></a>
	</div>
	<div id="main">
		<div class="white-block">
			<span class="menu-button" onclick="toggleNav()">&larr;Meniu</span>
			<h3>{{ pacient }} nu mai e în program. Ștergere efectuată cu succes.</h3>
		</div>
	</div>

</body>